/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SummaryReportClass */

#ifndef _Included_SummaryReportClass
#define _Included_SummaryReportClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SummaryReportClass
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_SummaryReportClass_getIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
