/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SummaryReportClass */

#ifndef _Included_SummaryReportClass
#define _Included_SummaryReportClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SummaryReportClass
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SummaryReportClass_nativeMethod
  (JNIEnv *, jobject);

/*
 * Class:     SummaryReportClass
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SummaryReportClass_modifyInstanceVariable
  (JNIEnv *, jobject);

/*
 * Class:     SummaryReportClass
 * Method:    GetSummaryReport
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SummaryReportClass_GetSummaryReport
  (JNIEnv *, jobject);

/*
 * Class:     SummaryReportClass
 * Method:    GetAverage
 * Signature: (III)F
 */
JNIEXPORT jfloat JNICALL Java_SummaryReportClass_GetAverage
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     SummaryReportClass
 * Method:    GetAverageArray
 * Signature: ([I)F
 */
JNIEXPORT jfloat JNICALL Java_SummaryReportClass_GetAverageArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
